### ISSUE TITLE
Keeping the existing material on objects

### ISSUE THREAD

**Issue by meah** [toxicFork/Unity3D-Plane-Clipping#2]
hi, i tried this script and it was great, what i want is to keep the material that i already have in my 3D objects

**Comment by Shinao** [comment]
In `ClippableObject.cs` - Remove the two lines inside OnEnable and put
`renderer.sharedMaterial.shader = Shader.Find("Custom/StandardClippable");`
It will automatically try to transfer everything to the new shader.

**Comment by meah** [comment]
thank you, it was helpfull, did you know how we can ignore the collider of clipped side ??
we already tried a script that cut the object using the plane but that one take lot of time to validate all meshes

**Comment by Shinao** [comment]
Nope sorry. Actually I stopped using this shader and created my own, seems counter intuitive to recreate the whole standard shader.
Honestly the only way to do what you want I think is to move and resize your collider while you move the clip planes. But yeah, could be cpu intensive.

**Comment by meah** [comment]
it will not work if i only move or resize the collider because i'm using the mesh collider
thanks for your help

**Comment by toxicFork** [comment]
Unfortunately with colliders we may not have the same flexibility as it goes into PhysX which may not allow it :(

**Comment by ghost** [comment]
hi!

If you can ... apply the script to a null container and make the cutting plane follow the container ... or it's almost useless because you have to always move the plane and it does not work on more meshes together
