### ISSUE TITLE
Build errors on windows standalone

### ISSUE THREAD

**Issue by tomekkie** [toxicFork/Unity3D-Plane-Clipping#3]
I am getting these errors on windows standalone:
Shader error in 'Custom/StandardClippable': invalid subscript 'posWorld' at Assets/PlaneClipping/Shaders/standard_clipped.cginc(242) (on d3d9)
Shader error in 'Custom/StandardClippable': invalid subscript 'posWorld' at Assets/PlaneClipping/Shaders/standard_clipped.cginc(242) (on d3d11)
Shader error in 'Custom/StandardClippable': invalid subscript 'posWorld' at Assets/PlaneClipping/Shaders/standard_clipped.cginc(242) (on d3d11_9x)
And the same for Custom/StandardSpecularClippable shader.
But the build itself seems to work on PC.
And similar ones when building for Android:
Shader error in 'Custom/StandardClippable': 'posWorld' :  no such field in structure; '' : unsupported construction; 'assign' :  cannot convert from 'vec4' to 'structure' at Assets/PlaneClipping/Shaders/standard_clipped.cginc(242) (on gles)
Shader error in 'Custom/StandardClippable': invalid subscript 'posWorld' at Assets/PlaneClipping/Shaders/standard_clipped.cginc(242) (on gles3)
Shader error in 'Custom/StandardClippable': 'posWorld' :  no such field in structure; 'constructor' : can't convert; 'FragmentSetup' :  unable to suitably promote arguments to function at Assets/PlaneClipping/Shaders/standard_clipped.cginc(303) (on gles)
And build is not working, while worked with previous version.

**Comment by gerwalk** [comment]
Same problem for Mac OSX standalone, Unity 5.6.3p1

`Shader error in 'Custom/StandardClippable': invalid subscript 'posWorld' at Assets/Shaders/standard_clipped.cginc(242) (on metal)`
`Shader error in 'Custom/StandardClippable': invalid subscript 'posWorld' at Assets/Shaders/standard_clipped.cginc(242) (on glcore)`
`Shader error in 'Custom/StandardSpecularClippable': invalid subscript 'posWorld' at Assets/Shaders/standard_clipped.cginc(242) (on metal)`
`Shader error in 'Custom/StandardSpecularClippable': invalid subscript 'posWorld' at Assets/Shaders/standard_clipped.cginc(242) (on glcore)`

**Comment by toxicFork** [comment]
Looks like it may be related to #4 , does that fix make it work for you two?
