### ISSUE TITLE
Couldn't get it to work on Android

### ISSUE THREAD

**Issue by tomekkie** [toxicFork/Unity3D-Plane-Clipping#4]
and Unity 5.6 editor at all.
getting "invalid worldPos subscript" errors. 
There seems to be an obvious error in standard_clipped.cginc.
I have just replaced all occurences of "VertexOutputDeferred" with "VertexOutputDeferredClip" and all the errors have gone.

**Comment by mshagin** [comment]
Wow! Thanks for this fix! It works on iOS as well.
